/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OauthDebugRouteImport } from './routes/oauth-debug'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapDebugRouteImport } from './routes/map-debug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfigDebugRouteImport } from './routes/config-debug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTripRouteImport } from './routes/_authenticated/trip'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedSharingRouteImport } from './routes/_authenticated/sharing'
import { Route as AuthenticatedRideRouteImport } from './routes/_authenticated/ride'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedBenefitsRouteImport } from './routes/_authenticated/benefits'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth.callback.index'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicAuthBeaconRouteImport } from './routes/api/public/auth-beacon'
import { Route as ApiNativeSosRouteImport } from './routes/api/native/sos'
import { Route as ApiInternalSosDispatchRouteImport } from './routes/api/internal/sos-dispatch'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthCallbackNMarcadorRouteImport } from './routes/auth.callback.n.$marcador'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthDebugRoute = OauthDebugRouteImport.update({
  id: '/oauth-debug',
  path: '/oauth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapDebugRoute = MapDebugRouteImport.update({
  id: '/map-debug',
  path: '/map-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigDebugRoute = ConfigDebugRouteImport.update({
  id: '/config-debug',
  path: '/config-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripRoute = AuthenticatedTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharingRoute = AuthenticatedSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRideRoute = AuthenticatedRideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenefitsRoute = AuthenticatedBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCallbackRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthBeaconRoute = ApiPublicAuthBeaconRouteImport.update({
  id: '/api/public/auth-beacon',
  path: '/api/public/auth-beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeSosRoute = ApiNativeSosRouteImport.update({
  id: '/api/native/sos',
  path: '/api/native/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalSosDispatchRoute = ApiInternalSosDispatchRouteImport.update({
  id: '/api/internal/sos-dispatch',
  path: '/api/internal/sos-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackNMarcadorRoute = AuthCallbackNMarcadorRouteImport.update({
  id: '/n/$marcador',
  path: '/n/$marcador',
  getParentRoute: () => AuthCallbackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config-debug': typeof ConfigDebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/map-debug': typeof MapDebugRoute
  '/mcp': typeof McpRoute
  '/oauth-debug': typeof OauthDebugRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ride': typeof AuthenticatedRideRoute
  '/sharing': typeof AuthenticatedSharingRoute
  '/sos': typeof AuthenticatedSosRoute
  '/trip': typeof AuthenticatedTripRoute
  '/auth/callback': typeof AuthCallbackRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/sos-dispatch': typeof ApiInternalSosDispatchRoute
  '/api/native/sos': typeof ApiNativeSosRoute
  '/api/public/auth-beacon': typeof ApiPublicAuthBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/auth/callback/n/$marcador': typeof AuthCallbackNMarcadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config-debug': typeof ConfigDebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/map-debug': typeof MapDebugRoute
  '/mcp': typeof McpRoute
  '/oauth-debug': typeof OauthDebugRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ride': typeof AuthenticatedRideRoute
  '/sharing': typeof AuthenticatedSharingRoute
  '/sos': typeof AuthenticatedSosRoute
  '/trip': typeof AuthenticatedTripRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/sos-dispatch': typeof ApiInternalSosDispatchRoute
  '/api/native/sos': typeof ApiNativeSosRoute
  '/api/public/auth-beacon': typeof ApiPublicAuthBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/auth/callback/n/$marcador': typeof AuthCallbackNMarcadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/config-debug': typeof ConfigDebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/map-debug': typeof MapDebugRoute
  '/mcp': typeof McpRoute
  '/oauth-debug': typeof OauthDebugRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/benefits': typeof AuthenticatedBenefitsRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/ride': typeof AuthenticatedRideRoute
  '/_authenticated/sharing': typeof AuthenticatedSharingRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/trip': typeof AuthenticatedTripRoute
  '/auth/callback': typeof AuthCallbackRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/sos-dispatch': typeof ApiInternalSosDispatchRoute
  '/api/native/sos': typeof ApiNativeSosRoute
  '/api/public/auth-beacon': typeof ApiPublicAuthBeaconRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/auth/callback/n/$marcador': typeof AuthCallbackNMarcadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config-debug'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/map-debug'
    | '/mcp'
    | '/oauth-debug'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/alerts'
    | '/benefits'
    | '/community'
    | '/contacts'
    | '/dashboard'
    | '/history'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/ride'
    | '/sharing'
    | '/sos'
    | '/trip'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/sos-dispatch'
    | '/api/native/sos'
    | '/api/public/auth-beacon'
    | '/api/public/whatsapp-webhook'
    | '/auth/callback/'
    | '/auth/callback/n/$marcador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config-debug'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/map-debug'
    | '/mcp'
    | '/oauth-debug'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/alerts'
    | '/benefits'
    | '/community'
    | '/contacts'
    | '/dashboard'
    | '/history'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/ride'
    | '/sharing'
    | '/sos'
    | '/trip'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/sos-dispatch'
    | '/api/native/sos'
    | '/api/public/auth-beacon'
    | '/api/public/whatsapp-webhook'
    | '/auth/callback'
    | '/auth/callback/n/$marcador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/config-debug'
    | '/forgot-password'
    | '/intro'
    | '/login'
    | '/map-debug'
    | '/mcp'
    | '/oauth-debug'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/benefits'
    | '/_authenticated/community'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/map'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/ride'
    | '/_authenticated/sharing'
    | '/_authenticated/sos'
    | '/_authenticated/trip'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/sos-dispatch'
    | '/api/native/sos'
    | '/api/public/auth-beacon'
    | '/api/public/whatsapp-webhook'
    | '/auth/callback/'
    | '/auth/callback/n/$marcador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConfigDebugRoute: typeof ConfigDebugRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  MapDebugRoute: typeof MapDebugRoute
  McpRoute: typeof McpRoute
  OauthDebugRoute: typeof OauthDebugRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiInternalSosDispatchRoute: typeof ApiInternalSosDispatchRoute
  ApiNativeSosRoute: typeof ApiNativeSosRoute
  ApiPublicAuthBeaconRoute: typeof ApiPublicAuthBeaconRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-debug': {
      id: '/oauth-debug'
      path: '/oauth-debug'
      fullPath: '/oauth-debug'
      preLoaderRoute: typeof OauthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-debug': {
      id: '/map-debug'
      path: '/map-debug'
      fullPath: '/map-debug'
      preLoaderRoute: typeof MapDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-debug': {
      id: '/config-debug'
      path: '/config-debug'
      fullPath: '/config-debug'
      preLoaderRoute: typeof ConfigDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trip': {
      id: '/_authenticated/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof AuthenticatedTripRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sharing': {
      id: '/_authenticated/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof AuthenticatedSharingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ride': {
      id: '/_authenticated/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof AuthenticatedRideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benefits': {
      id: '/_authenticated/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof AuthCallbackRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-beacon': {
      id: '/api/public/auth-beacon'
      path: '/api/public/auth-beacon'
      fullPath: '/api/public/auth-beacon'
      preLoaderRoute: typeof ApiPublicAuthBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/sos': {
      id: '/api/native/sos'
      path: '/api/native/sos'
      fullPath: '/api/native/sos'
      preLoaderRoute: typeof ApiNativeSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/sos-dispatch': {
      id: '/api/internal/sos-dispatch'
      path: '/api/internal/sos-dispatch'
      fullPath: '/api/internal/sos-dispatch'
      preLoaderRoute: typeof ApiInternalSosDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/n/$marcador': {
      id: '/auth/callback/n/$marcador'
      path: '/n/$marcador'
      fullPath: '/auth/callback/n/$marcador'
      preLoaderRoute: typeof AuthCallbackNMarcadorRouteImport
      parentRoute: typeof AuthCallbackRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBenefitsRoute: typeof AuthenticatedBenefitsRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRideRoute: typeof AuthenticatedRideRoute
  AuthenticatedSharingRoute: typeof AuthenticatedSharingRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedTripRoute: typeof AuthenticatedTripRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBenefitsRoute: AuthenticatedBenefitsRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRideRoute: AuthenticatedRideRoute,
  AuthenticatedSharingRoute: AuthenticatedSharingRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedTripRoute: AuthenticatedTripRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthCallbackRouteChildren {
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  AuthCallbackNMarcadorRoute: typeof AuthCallbackNMarcadorRoute
}

const AuthCallbackRouteChildren: AuthCallbackRouteChildren = {
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  AuthCallbackNMarcadorRoute: AuthCallbackNMarcadorRoute,
}

const AuthCallbackRouteWithChildren = AuthCallbackRoute._addFileChildren(
  AuthCallbackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConfigDebugRoute: ConfigDebugRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  MapDebugRoute: MapDebugRoute,
  McpRoute: McpRoute,
  OauthDebugRoute: OauthDebugRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiInternalSosDispatchRoute: ApiInternalSosDispatchRoute,
  ApiNativeSosRoute: ApiNativeSosRoute,
  ApiPublicAuthBeaconRoute: ApiPublicAuthBeaconRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
